name: Feature Request
description: Vorschlag für ein neues Feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem soll das Feature lösen?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Wie könnte die Lösung aussehen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen, die du erwogen hast
