"""Übersetzungen für die HTML-Berichte (separat von HA-UI-Translations)."""
from __future__ import annotations

LANG_DE = "de"
LANG_EN = "en"
SUPPORTED_LANGUAGES = [LANG_DE, LANG_EN]
DEFAULT_LANGUAGE = LANG_DE


MONTHS = {
    LANG_DE: [
        "", "Januar", "Februar", "März", "April", "Mai", "Juni",
        "Juli", "August", "September", "Oktober", "November", "Dezember",
    ],
    LANG_EN: [
        "", "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ],
}

MONTHS_SHORT = {
    LANG_DE: ["", "Jan", "Feb", "Mär", "Apr", "Mai", "Jun",
              "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
    LANG_EN: ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
}

WEEKDAYS_SHORT = {
    LANG_DE: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    LANG_EN: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
}


STRINGS = {
    LANG_DE: {
        "html_lang": "de",
        "brand_subtitle": "Verbrauchsbericht",
        "monthly_report": "Monatsbericht",
        "yearly_report": "Jahresbericht",
        "report": "Bericht",
        "generated_on": "erstellt am",
        "footer": (
            "Erstellt mit der Haushaltsdoku-Integration für Home Assistant. "
            "Quelle: Long-Term-Statistics."
        ),
        "overview": "Übersicht",
        "back_to_overview": "← Übersicht",
        "year": "Jahr",
        "yearly_reports": "Jahresberichte",
        "monthly_reports": "Monatsberichte",
        "custom_ranges": "Eigene Zeiträume",
        "no_reports_yet": "Noch keine Berichte. Rufe einen Service auf, um den ersten zu erzeugen.",
        "total": "Gesamt",
        "average_per_day": "Durchschnitt / Tag",
        "average_per_month": "Durchschnitt / Monat",
        "peak": "Höchstwert",
        "cost": "Kosten",
        "consumption": "Verbrauch",
        "data_table": "Datentabelle",
        "entries": "Einträge",
        "day": "Tag",
        "month": "Monat",
        "no_data": "Keine Daten im Zeitraum",
        "on_date": "am",
        # date format Day → "Mo, 01.04.2026"
        "fmt_day_full": "{wd}, {dd}.{mm}.{yyyy}",
        "fmt_day_short": "{dd}.{mm}.",
        # "April 2026"
        "fmt_month_year": "{month} {yyyy}",
        # arrows
        "prev_arrow": "←",
        "next_arrow": "→",
    },
    LANG_EN: {
        "html_lang": "en",
        "brand_subtitle": "Consumption report",
        "monthly_report": "Monthly report",
        "yearly_report": "Yearly report",
        "report": "Report",
        "generated_on": "generated on",
        "footer": (
            "Generated by the Haushaltsdoku integration for Home Assistant. "
            "Source: long-term statistics."
        ),
        "overview": "Overview",
        "back_to_overview": "← Overview",
        "year": "Year",
        "yearly_reports": "Yearly reports",
        "monthly_reports": "Monthly reports",
        "custom_ranges": "Custom ranges",
        "no_reports_yet": "No reports yet. Call a service to create the first one.",
        "total": "Total",
        "average_per_day": "Average / day",
        "average_per_month": "Average / month",
        "peak": "Peak",
        "cost": "Cost",
        "consumption": "Consumption",
        "data_table": "Data table",
        "entries": "entries",
        "day": "Day",
        "month": "Month",
        "no_data": "No data in this period",
        "on_date": "on",
        "fmt_day_full": "{wd}, {yyyy}-{mm}-{dd}",
        "fmt_day_short": "{dd}/{mm}",
        "fmt_month_year": "{month} {yyyy}",
        "prev_arrow": "←",
        "next_arrow": "→",
    },
}


def t(lang: str, key: str) -> str:
    """Translate a key. Falls back to default language."""
    if lang not in STRINGS:
        lang = DEFAULT_LANGUAGE
    return STRINGS[lang].get(key, STRINGS[DEFAULT_LANGUAGE].get(key, key))


def month_name(lang: str, month: int) -> str:
    if lang not in MONTHS:
        lang = DEFAULT_LANGUAGE
    return MONTHS[lang][month]


def month_short(lang: str, month: int) -> str:
    if lang not in MONTHS_SHORT:
        lang = DEFAULT_LANGUAGE
    return MONTHS_SHORT[lang][month]


def weekday_short(lang: str, weekday: int) -> str:
    """weekday: 0=Mon … 6=Sun (Python's date.weekday())."""
    if lang not in WEEKDAYS_SHORT:
        lang = DEFAULT_LANGUAGE
    return WEEKDAYS_SHORT[lang][weekday]


def format_date_full(lang: str, date) -> str:
    return t(lang, "fmt_day_full").format(
        wd=weekday_short(lang, date.weekday()),
        dd=f"{date.day:02d}",
        mm=f"{date.month:02d}",
        yyyy=date.year,
    )


def format_date_short(lang: str, date) -> str:
    return t(lang, "fmt_day_short").format(
        dd=f"{date.day:02d}",
        mm=f"{date.month:02d}",
        yyyy=date.year,
    )


def format_month_year(lang: str, date) -> str:
    return t(lang, "fmt_month_year").format(
        month=month_name(lang, date.month),
        yyyy=date.year,
    )


def format_number(value: float, digits: int = 2, lang: str = DEFAULT_LANGUAGE) -> str:
    """Locale-aware number formatting."""
    s = f"{value:,.{digits}f}"
    if lang == LANG_DE:
        # 1,234.56 → 1.234,56
        return s.replace(",", "#").replace(".", ",").replace("#", ".")
    # English: 1,234.56 (default)
    return s
